### ISSUE TITLE
spcosa dependency error while publishing an app with shiny

### ISSUE THREAD

**Issue by jars48** [edzer/sp#100]
A spcosa dependency error appeared while publishing an app with shiny.

**Comment by edzer** [comment]
What does that have to do with `sp`?

**Comment by jars48** [comment]
Dear Edzer,

Today, run my program and everything work perfect. Before, the problem 
was bacause of dependency with package spcosa. Maybe, this because of 
raster or gdal packages. I think the thread can be deleted. Thank you 
for your letter.

# Edtree_v08b_13022021
# Arseniy Zhogolev

# Install packages
#install.packages (c('rpart', 'evtree', 'partykit', 'raster', 'sp', 
'rgdal', 'shiny'))

# Load packages
#require(rpart) # CART algorithm implementation
#require(evtree) # EVTREE decision tree algorithm
#require(partykit) # tools for decision tree models edition
require(rgdal) # GDAL interface
require(raster) # tools for working with raster spatial data
require(sp) # tools for working with spatial data
require(shiny) # WEB GUI

# Variables initialization
#WD <- "G:/GIS/SASMs/EdTree_R/" # working directory

# Main script
#setwd(WD) # set working directory

r <- raster ("n50_e040_3arc_v2.tif") # import raster

# User interface
ui <- fluidPage(
   titlePanel("EdTree"),

   sidebarLayout(
     sidebarPanel(
       helpText("Heighs on digital elevation model, m"),

       sliderInput("range",
                   label = "Range of interest:",
                   min = -100, max = r@data@max/40, value = c(0, 300))
     ),

     mainPanel(plotOutput("map"))
   )
)

04.03.2021 15:48, Edzer Pebesma пишет:

**Comment by edzer** [comment]
`spcosa` was removed from CRAN; maybe you should contact its maintainer: it needs maintenance.
