### ISSUE TITLE
char2dms rounds degrees incorrectly

### ISSUE THREAD

**Issue by ArturoSbr** [edzer/sp#109]
I stumbled upon [an issue today](https://stackoverflow.com/questions/69484220/convert-dms-coordinates-to-decimal-degrees-in-r/69485865?noredirect=1#comment122818119_69485865). It seems that `sp::char2dms` rounds degrees incorrectly when the latitude and longitude inputs are missing the trailing North/South or East/West characters.

To see this, suppose my inputs don't have a trailing character.
```r
# Inputs without trailing character
> lat <- '21d11m24.32s'
> lng <- '104d38m26.88s'
# Convert to degrees
> lat_d <- char2dms(lat, chd='d', chm='m', chs='s') %>% as.numeric()
> lng_d <- char2dms(lng, chd='d', chm='m', chs='s') %>% as.numeric()
# Incorrect decimal degrees
> print(c(lat_d, lng_d))
[1]  21.18333 104.63333
```
The output changes when I add a trailing character to my inputs.
```r
# Inputs without trailing character
> lat <- '21d11m24.32sN'
> lng <- '104d38m26.88sW'
# Convert to degrees
> lat_d <- char2dms(lat, chd='d', chm='m', chs='s') %>% as.numeric()
> lng_d <- char2dms(lng, chd='d', chm='m', chs='s') %>% as.numeric()
# Incorrect decimal degrees
> print(c(lat_d, lng_d))
[1]   21.19009 -104.64080
```
Never mind the change from 104 to -104. My concern is that the degrees are rounded incorrectly when the trailing character is missing.

**Comment by edzer** [comment]
Yes, in the former case the seconds get ignored. But the documentation states: " In char2dms, the input data vector should use a regular format, such as that used in the PROJ.4 library, with a trailing capital (NSWE) indicating compass direction." I'd agree that an error message would be more helpful than a wrong result, but the error is on your side.
