### ISSUE TITLE
Speeding up over()

### ISSUE THREAD

**Issue by jsocolar** [edzer/sp#11]
I've noticed that when using over() to check for overlap between detailed/intricate polygons (or even points and intricate polygons), I can dramatically speed up the operation for non-overlapping geometries with non-overlapping extents by first comparing the extents and giving the appropriate output if they don't overlap.

Is there a reason not to wrap this inside the over() function? Any pathological way for it to fail?

**Comment by edzer** [comment]
No, there is no particular reason.

**Comment by jsocolar** [comment]
Cool--I'll submit a pull request sometime next week when I have time.

**Comment by edzer** [comment]
Any reason to keep this issue open?
