### ISSUE TITLE
R version requirement

### ISSUE THREAD

**Issue by ms609** [edzer/sp#143]
Hi,

When trying to install sp on R 3.6.3, installation fails with 

 > object 'palette.colors' is not exported by 'namespace:grDevices'

The sp DESCRIPTION file specifies `Depends: R (≥ 3.5.0)`, but `palette.colors` was not added until after R3.6. 
Does the DESCRIPTION file need updating, or can the use of `palette.colors` be avoided, for example by `if (packageVersion("base") <= "3.6.3") /*manual workaround*/ else palette.colors`?

Thanks,

Martin

**Comment by edzer** [comment]
are you sure this is caused by `sp`?

**Comment by ms609** [comment]
You're right, the issue was not with `sp` – apologies for the error.
