### ISSUE TITLE
FR: plot method for GridTopology

### ISSUE THREAD

**Issue by MichaelChirico** [edzer/sp#17]
There's currently no `plot` (nor `spplot`) method for `GridTopology` objecs -- the only option is to convert to `SpatialPolygons` first, which can be slow for bigger grids. 

It seems if all we want to do is preview the grid, `as.SpatialPolygons.GridTopology` may be overkill in such cases.

**Comment by edzer** [comment]
Try

```
> library(sp)
> gt = GridTopology(c(0,0), c(1,1), c(10,10))
> plot(SpatialGrid(gt))
```

`spplot` is not supposed to plot this, as there are no attributes (it doesn't plot `SpatialPolygons` either).
