### ISSUE TITLE
Dox clarification

### ISSUE THREAD

**Issue by MichaelChirico** [edzer/sp#18]
In `?GridTopology`, we have:

> `cellcentre.offset`     `numeric`; vector with the smallest coordinates for each dimension

To me, this reads as `cellcentre.offset` is the lower-left corner of the output grid;

In fact, it's the lower-left _centroid_ of the output grid.

This indeed jives with the documentation as stands, since `coordinates(grid)` will return the lower-left centroid.

However I think it would be helpful to add a short note about this distinction in the documentation, e.g.,

> `cellcentre.offset`     `numeric`; vector with the smallest centroid coordinates for each dimension

**Comment by edzer** [comment]
Where does your terminology come from? I see, in the same [sentence](https://github.com/edzer/sp/blob/master/man/GridTopology-class.Rd#L24-L25), that _coordinates refer to cell center_. How much clearer can it get? Anyway, I added "centroid" upon your wish.

**Comment by MichaelChirico** [comment]
Oh -- I'm running 1.2-3. That phrasing is new. I should have checked the development version. Thank you.

**Comment by edzer** [comment]
You're right, we were looking at different documentation objects; fixed the other one too.
