### ISSUE TITLE
issue in rasterize

### ISSUE THREAD

**Issue by spedygiorgio** [edzer/sp#19]
I was trying to rasterize a SpatialPolygonDataFrame but it seems to throw an error. A similar issue has been posted in SO [http://gis.stackexchange.com/questions/64343/r-raster-package-rasterize-failingno-slots](SO). dataset attached.
[geodata.zip](https://github.com/edzer/sp/files/701734/geodata.zip)

Code that throws an error below: 

`grandine.raster<-rasterize(x=grandineMap,y=fulminazione,grandineMap$GRIDCODE,fun=mean,na.rm=TRUE)`

**Comment by Nowosad** [comment]
@spedygiorgio `rasterize` is not a function from package `sp`, but is a function from package `raster`.

**Comment by spedygiorgio** [comment]
Right sorry for the error

Il gio 12 gen 2017, 14:26 Jakub Nowosad <notifications@github.com> ha
scritto:

**Comment by edzer** [comment]
Answer is on SO.
