### ISSUE TITLE
Processing of a 1.5 gigabytes dataset with point in polygon method eats up all my 16GB RAM

### ISSUE THREAD

**Issue by kun-zhou** [edzer/sp#22]
I was running the following code, where  `pickup2.csv` is a 1.5 gigabytes uncompressed `csv` file containing two columns, one latitude and another longitude. The shape file contains polygons of and is around 1.5 MB. The goal is to find the name of the polygon each gps location is in and append it as an additional column to the original dataset. the issue is after waiting for around 8 minutes, my system becomes unresponsive and all my 16 GB of RAM are allocated to R. I tested it a few times with the same result. I end up splitting the csv file into 10 csv files each with 4 million rows and concatenated them after processing, it works fine. The issue is why is this function taking up so much memory while the data files are small compared to my RAM.

 Here is the code:
```
library(rgeos)
library(sp)
library(rgdal)

infile <- "pickup2.csv"
ny.map <- readOGR("gps2neighborhood/ZillowNeighborhoods-NY.shp")
drop <- read.csv(infile)
coordinates(drop.locs) <- c(1,2)
proj4string(drop.locs) <- proj4string(ny.map)
drop.ngbh <- over(drop.locs, ny.map)
```

**Comment by edzer** [comment]
What is `object.size(drops.locs)` and `object.size(ny.map)`?

**Comment by kun-zhou** [comment]
Thanks for replying. The first drops.locs is 1071196328 bytes the second is 3384344 bytes.

Kun

**Comment by edzer** [comment]
What is your `sessionInfo()$platform`?

**Comment by kun-zhou** [comment]
R version 3.3.2 (2016-10-31)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 25 (Twenty Five)

**Comment by edzer** [comment]
What happens if you leave out loading `rgeos` in the script above?

**Comment by kun-zhou** [comment]
Still no luck, the process killed itself after using up almost all of my RAM like before.

**Comment by edzer** [comment]
I tried a problem of similar size, and it goes indeed in the direction of using 16Gb and more; I killed it before it killed my machine. It seems like this size of problem is beyond the limit of what sp can handle with this size of computer.
