### ISSUE TITLE
Error in spDistsN1(): "sp_dists" not available for .C()

### ISSUE THREAD

**Issue by thlytras** [edzer/sp#32]
```
> library(sp)
> ll <- matrix(c(5, 6, 60, 60), ncol=2)
> km <- spDistsN1(ll, ll[1,], longlat=TRUE)
Error in .C("sp_dists", x, y, xx, yy, n, dists, lonlat, PACKAGE = "sp") : 
  "sp_dists" not available for .C() for package "sp"
```

Something's wrong with function spDistsN1(), and I can't believe I'm the only one whose [package](https://github.com/thlytras/rfgfs) is broken by this....
I'm on latest Debian testing amd64, R is version 3.4.0-1, sp is 1.2-4-1 (from debian repo).

**Comment by edzer** [comment]
I can't reproduce this problem on ubuntu 16.04. Please reinstall `sp` from source, and try again - a possibility would be you have a binary that was compiled under R 3.3.x

**Comment by thlytras** [comment]
That was exactly it, thanks! I compiled from source and it worked.
I'll send a bug report to debian for that, probably the package needs to be recompiled for R 3.4.x.
