### ISSUE TITLE
Error when using spDistsN1 under R 3.4.0

### ISSUE THREAD

**Issue by SteffenKothe** [edzer/sp#33]
Hi,
recently my workstation was updated to R 3.4.0. The code, which was working perfectly under R 3.3, causes now an error.
Here is an example:

```
lat1 <- 50
lon1 <- 10
lat2 <- 51
lat2 <- 11
pos <- SpatialPoints(cbind(lon1,lat1), proj4string=CRS("+proj=longlat +datum=WGS84"))
dist <- spDistsN1(pos, c(lon2,lat2), longlat = FALSE)
Error in .C("sp_dists", x, y, xx, yy, n, dists, lonlat, PACKAGE = "sp") : 
  'sp_dists' ist nicht verfügbar für .C() aus Paket "sp"

```
 ('sp_dists' is not available for .C() from package "sp")

I'm using this function in one of my packages and some functions strongly depend on it. Thus, it would be great if you have any suggestion on how to solve this issue.

Thanks for your help.

**Comment by edzer** [comment]
See #32.

**Comment by SteffenKothe** [comment]
Thanks for your help and sorry, I didi't realize the closed issue.
Wer lesen kann ...
