### ISSUE TITLE
(re-)allow polygons with < 4 vertices?

### ISSUE THREAD

**Issue by mpadge** [edzer/sp#37]
This is currently allowed
```
Sr5 <- Polygon (rbind (c (1, 1)))
```
with the warning from [`SpatialPolygons-methods.R`](https://github.com/edzer/sp/blob/master/R/SpatialPolygons-methods.R#L37-L42). At present, `sp` generates polygons that are both (i) potentially nonsensical through being non-polygonal and (ii) inconsistent with `sf` output. These two problems could at least be reduced to just one by implementing one (and only one!) of:

1. Prevent construction of `Polygon` objects from non-polygonal data, thereby at least prohibiting nonsense; or
2. Just let nonsense be nonsense and revert to allowing <4 vertices (through removing the insertion of extra rows in `sp::Polygon`), yielding results that would be consistent with `sf` handling of such objects.

cc @mdsumner

**Comment by edzer** [comment]
sp predates the simple feature standard and does not have the ambition to sync with that; changing basic behavior like this might affect legacy code in downstream packages.
