### ISSUE TITLE
wgs84 web mercator coordinates?

### ISSUE THREAD

**Issue by vinhdizzo** [edzer/sp#4]
Hi, first, thanks for the wonderful package.  It has allowed me, a non-GIS person, to do some useful analysis with shapefiles.

I have a question that will be easy for you to answer, in which I'm having a very difficult time to find the answer to.  I have an EPSG 3857 shapefile (WGS84, Web Mercator).  I read this into R using the `readOGR` function with the `p4s='+init=EPSG:3857'` argument.  I then use the `spTransform` function to re-project this to NAD83 with the argument `CRS('+proj=longlat +datum=NAD83')`.  This converts the coordinates into longitude/latitude.

Prior to the transformation, I see coordinates like the following:

```
         [,1]    [,2]
[1,] -9518097 3508157
[2,] -9518461 3508072
[3,] -9518457 3508134
[4,] -9518097 3508157
```

What units or coordinate system are these in exactly?  Could you point me to a reference?  My understanding is that the coordinates should be in UTM, which I expect to see a Zone, North/South specification, and a meter specification for the Easting and Northing.  However, I don't think this is what I see represented in the above example.  Could you point me in the right direction?  Thanks for your help.

**Comment by edzer** [comment]
They are in spherical Mercator, see for instance http://docs.openlayers.org/library/spherical_mercator.html or http://docs.openlayers.org/library/spherical_mercator.html.

**Comment by vinhdizzo** [comment]
Thanks! Very helpful. Are the meters/coordinates all relative to the equator and prime meridian?
