### ISSUE TITLE
identicalCRS bug?

### ISSUE THREAD

**Issue by choisy** [edzer/sp#40]
With the S1 and S2 spatial objects defined as below
```
m <- matrix(c(0, 0, 1, 1), ncol = 2, dimnames = list(NULL, c("min", "max")))
crs1 <- CRS("+proj=utm +zone=48 +ellps=WGS84 +units=m +no_defs")
crs2 <- CRS("+proj=utm +ellps=WGS84 +zone=48 +units=m +no_defs")
S1 <- Spatial(bbox = m, proj4string = crs1)
S2 <- Spatial(bbox = m, proj4string = crs2)
```
shouldn't we expect `identicalCRS(S1, S2)` to return `TRUE` instead of `FALSE`?

**Comment by edzer** [comment]
this was committed [here](https://github.com/edzer/sp/commit/6b7df7d1456f27410e43e662c0d55640053a7fcf).
