### ISSUE TITLE
identicalCRS() should employ CRS()

### ISSUE THREAD

**Issue by bastistician** [edzer/sp#46]
The change in #31 relaxed `identicalCRS()` to allow for permutations of projection arguments (which I think is a good idea). However, it also removed prior harmonisation of these strings via `CRS()` with package **rgdal**. This breaks previously working code (and one of my package vignettes).

Here is a minimal reproducible example:

```
library("sp")
stopifnot(requireNamespace("rgdal"))  # the error only occurs if rgdal is available
coords <- cbind(x = c(4288, 4289, 4281, 4284, 4288),
                y = c(3524, 3519, 3517, 3524, 3524))
p4s <- " +init=epsg:3035 +units=km +proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +no_defs"
x <- SpatialPolygons(list(Polygons(list(Polygon(coords)), ID = 1)),
                     proj4string = new("CRS", projargs = p4s))

spsample(x = x, n = 1, type = "random")
traceback()
## 7: stop(msg, call. = FALSE, domain = NA)
## 6: stopifnot(identicalCRS(x, y))
## 5: over(pts, geometry(x))
## 4: over(pts, geometry(x))
## 3: .local(x, n, type, ...)
## 2: spsample(x = x, n = 1, type = "random")
## 1: spsample(x = x, n = 1, type = "random")
```

The problem is that `CRS(p4s)@projargs`, i.e., `rgdal::checkCRSArgs(p4s)[[2]]` is not identical to the original `p4s`. The latter is used by the spatial object `x` in which to sample points, while the former is used by `pts` (the result of the `sample.Spatial()` call in `spsample()`).

Solution: I suggest to `strsplit` `CRS(x)` and `CRS(y)` instead of plain `x` and `y` in the new auxiliary function `identicalCRS1()`. Should I prepare a PR with this modification?

**Comment by edzer** [comment]
Thanks -- sounds like a plan!
