### ISSUE TITLE
image.SpatialGridDataFrame() needs useRasterImage = FALSE on windows 7 since 2 weeks

### ISSUE THREAD

**Issue by locherx** [edzer/sp#48]
I use image.SpatialGridDataFrame() of sp package since years on the same Lenovo Windows 7 machine. Thank you very much for the nice package. The Windows 7 is always updated with the most recent patches.

Since some days the image produced with image.SpatialGridDataFrame() did not appear any more neither on the screen nor in the png file. This effect did not depend neither from the version of R (V 2.3.4 up to V 3.4.4) and nor from the version of sp (V 1.2-2 up to V 1.2.7). It did not appear at all, even when I used the function only once after starting R (and even after rebooting the system).

The same code does run on other windows 7 Dell machines presumably not running with the latest patches. I guess that a recent patch has introduced this problem on my machine.  

Finally, I could fix the problem on my machine by setting the argument useRasterImage = FALSE in image.SpatialGridDataFrame(). It would have been helpful to find a comment with the argument useRasterImage in the help file like:
"rasterImage does not render properly on some Windows systems. In this case, set the argument to FALSE for legacy rendering". (In the help text, you still refer to !.isSDI(), which seems to not exist any more in the package).

Kind regards
René

**Comment by edzer** [comment]
Thanks! Yes, that was a bit sloppy of me. I hadn't anticipated that this was still necessary on windows.
