### ISSUE TITLE
'[' SpatialPoints method not working in parLapply()

### ISSUE THREAD

**Issue by CottonRockwood** [edzer/sp#5]
This may be an issue more related to `parLapply` than `sp`, but I'm looking for any help I can get.  When I try to run a spatial subset (SpatialPointsDataFrame subset by single SpatialPolygons) within parLapply(), the `sp` package loads on each worker, but I ultimately get an error:  "4 nodes produced errors; first error: object of type 'S4' is not subsettable".
The same happens with llply under the `plyr` package with .parallel=TRUE.  Base `lapply` works, however.  It appears that somehow the method for `[` for SpatialPoints is not being loaded on the workers even though the `sp` package is.  This doesn't make sense to me.  I have put a question on Stack Exchange (http://gis.stackexchange.com/q/188954/35320) regarding this if you would like more details.
Any thoughts or help is appreciated.

**Comment by edzer** [comment]
If it isn't an issue with `sp`, then why post here? Have you tried loading `methods` before `sp` is loaded? See https://stat.ethz.ch/pipermail/r-sig-geo/2016-April/024269.html

**Comment by CottonRockwood** [comment]
Hi Edzer-

Thanks for the reply and help.  I posted because I didn’t know if the problem might lie with sp or if it was normal behavior and I could not find that info anywhere.  Sorry for any inconvenience.

Best,

Cotton
