### ISSUE TITLE
_R_CHECK_LENGTH_1_LOGIC2_

### ISSUE THREAD

**Issue by bastistician** [edzer/sp#54]
Using the new experimental environment variable `_R_CHECK_LENGTH_1_LOGIC2_` in R-devel (https://github.com/wch/r-source/commit/bc49c27003064623acdf355957bc3423fc025cfd), I found the following problem in the `[`-method for class "SpatialPolygonsDataFrame":

https://github.com/edzer/sp/blob/e3b7b7c0d5b301e9fcc7ee3ef82cf8733532f356/R/SpatialPolygonsDataFrame-methods.R#L114

I guess this should be `any(i < 0)`.

Another issue is here:
https://github.com/edzer/sp/blob/e3b7b7c0d5b301e9fcc7ee3ef82cf8733532f356/R/SpatialPointsDataFrame-methods.R#L66
(The first `any` should close before the `||`.)

**Comment by edzer** [comment]
Thanks, @bastistician - well spotted!
