### ISSUE TITLE
length > 1 in coercion to logical

### ISSUE THREAD

**Issue by rhijmans** [edzer/sp#60]
On line 112-114 of SpatialPolygonsDataFrame-methods.R there is

	if (length(i) > 0) {
            y@bbox <- .Call(bboxCalcR_c, y@polygons)
            if (is.numeric(i) && i < 0) {

`i < 0` is problematic as it can return a vector longer than 1.  It works fine now, but apparently this will be an error in future R.  See 

https://github.com/rspatial/raster/issues/75
https://github.com/Jean-Romain/lidR/issues/292

**Comment by edzer** [comment]
This was solved in #54, but as of yet unreleased.

**Comment by HenrikBengtsson** [comment]
> ... but apparently this will be an error in future R

To be clear, this has *nothing* to do with the future framework - it's a bug in the sp package.

The reason why so many of these bug reports originate from future related code is that I run all my reverse packages dependency checks for future using `_R_CHECK_LENGTH_1_CONDITION_=verbose` and `_R_CHECK_LENGTH_1_LOGIC2_=verbose` and I spot lots of them and report upstream.

@edzer, is there an ETA for the next release?  This bug keeps hitting several of your downstream packages.

UPDATE 2019-11-07: To clarify, I misread "future R" by OP to involve the 'future' package bc we came to this one from future -> lidR -> sf. Oh well

**Comment by edzer** [comment]
I'll try to do that this week.
