### ISSUE TITLE
Add ASDAR 2ed comment description to help page

### ISSUE THREAD

**Issue by rsbivand** [edzer/sp#66]
ASDAR 2d, pp. 47-48 description needed in **sp** help pages and link to **rgeos** for analysing exterior/interior (pp. 132-133). Still not guaranteed to be valid because shapefiles treat interior rings touching exterior rings differently.

**Comment by rsbivand** [comment]
Ping @rsbivand @mdsumner

**Comment by edzer** [comment]
```r
library(sp)
?Polygons
```
and search for "comment"; see also sf/R/sp.R, and search for comment.

**Comment by mdsumner** [comment]
thanks, I see it's documented in `rgeos::createSPComment` also on [rforge only](https://r-forge.r-project.org/scm/viewvc.php/pkg/man/comment-functions.Rd?view=markup&root=rgeos), but can be browsed on the read-only github rforge mirror at https://github.com/rforge/rgeos/blob/master/pkg/man/comment-functions.Rd

**Comment by rsbivand** [comment]
The github mirror is useless, not supported by the maintainer, so by definition not where to go. Read the package help page at https://cran.r-project.org/package=rgeos, and find the maintainer-provided documentation site at http://rgeos.r-forge.r-project.org/index.html where http://rgeos.r-forge.r-project.org/reference/comment-functions.html provides the online version of ?createSPcomment.
