### ISSUE TITLE
error to warning for "Geographical CRS given to non-conformant data"

### ISSUE THREAD

**Issue by rhijmans** [edzer/sp#77]
In `raster`, I am changing direct access to the @proj4string slot, by using the `proj4string<-` method; in the hope that this will make the change in crs handling less painful. In some places that leads to the error below.  

```
library(sp)
s <- SpatialPoints(cbind(-200, 0))
proj4string(s) <- "+proj=longlat +datum=WGS84"
#Error in ReplProj4string(obj, CRS(value)) : 
#  Geographical CRS given to non-conformant data: -200
```` 

Could you change this error to a warning? It is often practical to have values outside of the normal range, particularly the longitude range.

**Comment by edzer** [comment]
I can only find an outcommented version of that error, which sp version do you use?

**Comment by rhijmans** [comment]
It is in develop and in the current CRAN. See `sp:::ReplProj4string`

**Comment by rhijmans** [comment]
And I now see that I (packages that depend on raster) can change the behavior with `set_ll_warn(TRUE)` to get a warning instead of an error. That should be good enough.
