### ISSUE TITLE
A error for use gridded

### ISSUE THREAD

**Issue by OrdinarySK** [edzer/sp#78]
when gridded(grid) <- ~longtitude+latitude

Error in if (max(object@grid.index) > .NumberOfCells(object@grid)) return("grid.index max value too large") : 
  need TRUE/FALSE Missing values should not be used in place of values
此外: Warning messages:
1: In points2grid(points, tolerance, round) :
  grid has empty column/rows in dimension 1
2: In points2grid(points, tolerance, round) :
  grid topology may be corrupt in dimension 1
3: In points2grid(points, tolerance, round) :
  grid has empty column/rows in dimension 2
4: In points2grid(points, tolerance, round) :
  grid topology may be corrupt in dimension 2
5: In getGridIndex(coordinates(points), grid) :
  NAs introduced by coercion to integer range

my data is as fllows:
latitude | slope | lst | evelation | precipitation | aspect | twi | longtitude
-- | -- | -- | -- | -- | -- | -- | --
3042330 | 10.6631 | 29.4972 | 1537 | 780 | 65.1363 | 5.176891 | 1132930
3317390 | 32.4593 | 12.1095 | 3307 | 864 | 72.5937 | 3.403342 | 1121580
3261620 | 31.0034 | 10.1276 | 4041 | 744 | 114.729 | 1.559861 | 1075480
3900180 | 5.98922 | 16.5291 | 4361 | 528 | 173.157 | 3.781343 | 1173290
3767690 | 10.2063 | 17.3061 | 966 | 888 | 218.108 | 2.918423 | 1138230
3512780 | 35.4287 | 13.0686 | 2689 | 744 | 344.254 | 1.221261 | 1150330
4006480 | 33.8619 | 11.9414 | 2597 | 600 | 35.5653 | 0.944801 | 1169030
4041400 | 5.11893 | 13.2081 | 1967 | 636 | 172.875 | 6.588634 | 1067850
4100410 | 4.38622 | 4.97455 | 4712 | 384 | 42.0643 | 3.141193 | 1043140
4079870 | 2.23272 | 11.0909 | 4565 | 300 | 4.08562 | 3.167998 | 1210750
3488500 | 12.4799 | 21.6926 | 931 | 1392 | 166.574 | 4.215748 | 1177310
3695280 | 8.91984 | 22.094 | 469 | 996 | 53.6371 | 5.591178 | 1162540

The previous step is:
grid <- read.csv("D:/RR/ggg.csv")
gridded(grid) <- ~longtitude+latitude

My coordinate is WGS_84 World Mercator

**Comment by edzer** [comment]
This lacks a reproducible example. Most likely, your points are not on a regular grid.

**Comment by OrdinarySK** [comment]
Thank you !
