### ISSUE TITLE
Maybe release 1.4-2 soon?

### ISSUE THREAD

**Issue by rsbivand** [edzer/sp#79]
It will be easier  to see what breaks with **rgdal** 1.5-8 as I move to release if current **sp** is on CRAN.

**Comment by edzer** [comment]
Shall I release as is in branch master now? I haven't run any revdep checks.

**Comment by rsbivand** [comment]
No, did you merge my PR #76 ? Please do that first. Once that is done, we can both run revdeps and I can check  against **rgdal** current trunk.

At the moment I'm struggling to get https://rgdal.r-forge.r-project.org/articles/CRS_projections_transformations.html to check cleanly on R-forge with its various PROJ and GDAL versions. I can't get the PROJ search path to behave either (I think it is reset in each new context). For the vignette, I've limited run to my platforms, but until >= 7 is predictable, I can't see a sensible resolution. I just wanted to show why WKT2 then CDN grids are worth the pain ...

**Comment by edzer** [comment]
#76 merged and revdep runs started. I'm afraid I'd have to hire someone to go through the revdep logs, though...

That's a great vignette! I think there's nothing wrong with compiling it locally, I do that with vignettes that require `starsdata` for instance. On the software side for automatic testing, travis and now GitHub actions may be easier to configure.

**Comment by rsbivand** [comment]
With released check OK,  with devel:

```
* checking dependencies in R code ... NOTE
Missing or unexported objects:
  ‘rgdal::checkCRSArgs_ng’ ‘rgdal::new_proj_and_gdal’
```

as before when checking with released **rgdal**. Checks OK on R devel with **rgdal** devel trunk.

**Comment by rsbivand** [comment]
The remaining vignette problem on Windows is in the 

```
demo(meuse, ask=FALSE, package="sp", echo=FALSE)
library(mapview)
mapview(meuse, zcol="zinc")
```
with error `cannot open the connection` which feels like the one to a browser. How do you handle those? Resolved by conditioning out Windows platforms (I hope),

**Comment by mdsumner** [comment]
I'd go through the revdep logs, will they be committed here? Are you using revdepcheck?  

I'll kick off a run myself

**Comment by edzer** [comment]
@rsbivand I've done this:
https://github.com/r-spatial/sf/blob/c6d97dbc0a70e85aebe1b06626abf591bacefe13/vignettes/sf5.Rmd#L196-L199

**Comment by edzer** [comment]
@mdsumner I use the following script
```
rm -fr /tmp/rdeps
mkdir /tmp/rdeps
cp sp_*gz /tmp/rdeps
(cd /tmp/rdeps; _R_CHECK_FORCE_SUGGESTS_=FALSE R --save -e 'r <- tools::check_packages_in_dir(".", which = c("Depends", "Imports", "LinkingTo", "Suggests", "Enhances"), check_args = "--no-vignettes --as-cran", reverse = list(recursive = FALSE), Ncpus = 2)')
```
Doing this interactively means there will still be a few packages waiting for you to close a window...

**Comment by rsbivand** [comment]
I revdep interactively, but drop problem packages like BIEN, which hangs on a link out to some data source. I'm almost done including vignettes, will try to post the results. So far very few packages error check, geoknife which has always failed as far as I can remember with a POSIX time formatting error, reproducible and rnfra with testthat errors not obviously to do with sp. Re-checking those that failed first time round probably because I upgraded to Fedora 32 last week, and probably have a few compiled packages using external libraries with ABI changes. Get back shortly.

**Comment by rsbivand** [comment]
This zipfile contains the 00check.log files of all not OK packages, and a CSV file of all packages tested. Many are just NOTES. The remaining ERROR are geoknife, reproducible and rnfra.
[check_logs.zip](https://github.com/edzer/sp/files/4648977/check_logs.zip)

**Comment by mdsumner** [comment]
Nice one

**Comment by mdsumner** [comment]
The rnfra one has nothing to do with sp. Is that the kind of go through that helps?  

It's a test failure on the dimensions of a data frame done with an `expect_equal` of an inequality. I'll PR a fix. 

I'll check the other two as well and then start on WARNINGS, but this seems small enough to proceed? (I don't have any perspective on what level you get to, I learnt quite a bit about what CRAN will accept only recently).

**Comment by rsbivand** [comment]
I'm looking at the warnings - so far two missing .sty files ... agridat, dartR, GADMTools, HSAUR3 cleared now. Let me know if you start the warnings ascending from Z*, please.

**Comment by mdsumner** [comment]
**rnrfa** PR: https://github.com/cvitolo/rnrfa/pull/22

(it's hard to pass check as it times out sometimes when reading data, but that might be compounded by my location)

**Comment by mdsumner** [comment]
**geoknife**

the check log attached above for geoknife errors in the vignette and looks like a date parsing problem, more serious is in the tests, the test fragment reprex is submitted here: 

https://github.com/USGS-R/geoknife/issues/387

there are other test errors that look unrelated to sp

**Comment by rsbivand** [comment]
agridat, dartR, GADMTools, HSAUR3, IDE, iemisc warnings cleared - suggested packages needed in vignettes or vignettes used LaTeX sty that I had not installed. Proceeding with warnings at MTA.

**Comment by mdsumner** [comment]
just starting on reproducible

**Comment by rsbivand** [comment]
Warnings: agridat, dartR, GADMTools, HSAUR3, IDE, iemisc, MTA, pavo, recmap, ref.ICAR, secrlinear cleared, sos4R is the same timeout as somme CRAN instances, looking at weathercan ... and weathercan cleared too. So we are left with plenty of NOTEs, but do we worry too much about those?

**Comment by mdsumner** [comment]
reproducible is pretty serious, and I won't be able to install gdalUtils atm - attached the testthat output
[reproducible_testoutput.txt](https://github.com/edzer/sp/files/4649575/reproducible_testoutput.txt)

**Comment by rsbivand** [comment]
I'll try **reproducible** with **rgdal** current trunk, the revdep checks I reported were with current **sp** master and released **rgdal**, **sf**, etc. Note that https://cran.r-project.org/web/checks/check_results_reproducible.html is pretty red.

**Comment by edzer** [comment]
I only see a harmless warning and a note for `reproducible`

<details>

```
* using log directory ‘/tmp/rdeps/reproducible.Rcheck’
* using R version 4.0.0 (2020-04-24)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* using options ‘--no-vignettes --as-cran’
* checking for file ‘reproducible/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘reproducible’ version ‘1.1.0’
* package encoding: UTF-8
* checking CRAN incoming feasibility ... WARNING
Maintainer: ‘Eliot J B McIntire <eliot.mcintire@canada.ca>’

Insufficient package version (submitted: 1.1.0, existing: 1.1.0)

Days since last update: 3
* checking package namespace information ... OK
* checking package dependencies ... NOTE
Imports includes 25 non-default packages.
Importing from so many packages makes the package vulnerable to any of
them becoming unavailable.  Move as many as possible to Suggests and
use conditionally.
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘reproducible’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking for future file timestamps ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking use of S3 registration ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ... OK
  Running ‘test-all.R’ [39s/69s]
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ... SKIPPED
* checking re-building of vignette outputs ... SKIPPED
* checking PDF version of manual ... OK
* checking for non-standard things in the check directory ... OK
* checking for detritus in the temp directory ... OK
* DONE
Status: 1 WARNING, 1 NOTE
```

</details>

**Comment by rsbivand** [comment]
Same errors in **reproducible** with trunk **rgdal** - the same Error: Filenames for environment (@test-misc.R#284) as in failing CRAN instances. I don't think this is caused by us.

```
> tmpdir <- tempdir()
>   rlogoFiles <- system.file("external/rlogo.grd", package="raster")
>   rlogoFiles <- c(rlogoFiles, gsub("grd$", "gri", rlogoFiles))
>   secondSet <- file.path(tmpdir, c("one.grd", "one.gri"))
>   file.link(rlogoFiles, secondSet)
[1] FALSE FALSE
Warning messages:
1: In file.link(rlogoFiles, secondSet) :
  cannot link '/home/rsb/lib/r_libs/raster/external/rlogo.grd' to '/tmp/RtmpGf42Rw/one.grd', reason 'Invalid cross-device link'
2: In file.link(rlogoFiles, secondSet) :
  cannot link '/home/rsb/lib/r_libs/raster/external/rlogo.gri' to '/tmp/RtmpGf42Rw/one.gri', reason 'Invalid cross-device link'
```

**Comment by rsbivand** [comment]
Most of the CRAN instances fail that package, it is certainly not our problem. So with Mike's help (thanks!), I think we're OK. I haven't checked the NOTE entries, but we'll hear back from CRAN on those if they are caused by this **sp** release.

**Comment by edzer** [comment]
So, shall I submit current master?

**Comment by rsbivand** [comment]
+1

**Comment by mdsumner** [comment]
+1

**Comment by edzer** [comment]
win-builder devel gives one NOTE:
```
* checking dependencies in R code ... NOTE
Missing or unexported objects:
  'rgdal::checkCRSArgs_ng' 'rgdal::new_proj_and_gdal'
```
but that is needed in anticipation of upcoming rgdal, right?

**Comment by rsbivand** [comment]
Yes, and was there for 1.4-1 too.

**Comment by edzer** [comment]
Submitted!

**Comment by edzer** [comment]
On CRAN now - thanks so much!!

**Comment by QuLogic** [comment]
Forgot to update `NEWS` again...
