### ISSUE TITLE
spplot中面图层无法显示！

### ISSUE THREAD

**Issue by fankk18** [edzer/sp#8]
spplot(idw['counttotal'],layout(1,1),as.table=TRUE,names.attr='',
                      xlim=bbox(chinaLine)[1,],ylim=bbox(chinaLine)[2,],col.regions=cols,
                      at=c(seq(0,3.6,0.4)),
                      colorkey=list(space='right',labels = list(at=c(0,0.8,1.6,2.4,3.2),cex=1.2,
                                                                fontface="bold",fontfimaly='Times')),
                      strip=strip.custom(par.strip.text=list(cex=1.2,font='bold',fontfamily='Times')),
                      sp.layout=list(lines2,lines1,list1,text1,lines3,poly))
sp.layout=list(lines2,lines1,list1,text1,lines3,poly),这句话中最后poly是一个面图层，但是怎么最后画的图，这个面图层显示不了，是不是面图层默认画在了最底层？怎么把面图层画在最上面？希望各位能帮助我解决这个问题！谢谢

**Comment by edzer** [comment]
Please see the `first=TRUE` or `first=FALSE` modifiers to `sp.layout` list items, this determines whehter something is drawn first, or last.

**Comment by fankk18** [comment]
THANK YOU VERY MUCH!
poly <- list('sp.polygons',noheatwave,col='#000000',fill = '#000000',which=c(1:6), first = FALSE)这条命令增加了 first = FALSE之后，可以实现想要的效果了！谢谢！大力出奇迹！
