### ISSUE TITLE
Documentation: ?over doesn't describe fn well

### ISSUE THREAD

**Issue by MichaelChirico** [edzer/sp#83]
`fn` is described as:

> (optional) a function; see value

However, `Value` section doesn't mention `fn` at all.

Methods mention when `fn` is valid but the description is inadequate.

I came to `?over` trying to see a better way to fix https://github.com/MichaelChirico/geohashTools/issues/30

Where the error is:

```
cover = cover[!drop(is.na(sp::over(cover, SP))), ]
```

was designed for `SpatialPoints` input and not robust to `SpatialPointsDataFrame` input.

My fix is

```
cover = cover[which(sapply(sp::over(cover, SP, returnList=TRUE), NROW) > 0L), ]
```

I was hoping `fn=NROW` would skip the `sapply(., NROW)` step & trying to learn why it wouldn't work, but I'm still not clear.

**Comment by edzer** [comment]
There is a vignette that describes what `over` does: https://cran.r-project.org/web/packages/sp/vignettes/over.pdf; if you see room for improving the docs of sp please provide a PR. `sp` is in maintenance mode, all development is recommended to use `sf` instead.

**Comment by MichaelChirico** [comment]
Duly noted, thanks
