### ISSUE TITLE
coordinates adds column to SpatialPointsDataFrame

### ISSUE THREAD

**Issue by plantarum** [edzer/sp#84]
Hi,

When I convert a data.frame to a SpatialPointsDataFrame, the column `optional` is appended to the result. I don't recall this from previous work, is it supposed to happen?

eg.:

``` R
data(meuse.grid)
coordinates(meuse.grid) <- ~x+y
head(data.frame(meuse.grid))
```
| |      x|      y| part.a| part.b|      dist| soil| ffreq| optional|
|--|------|------|---------|--------|------|---|---|---|
|1| 181180| 333740|      1|      0| 0.0000000|    1|     1|     TRUE|
|2| 181140| 333700|      1|      0| 0.0000000|    1|     1|     TRUE|
|3| 181180| 333700|      1|      0| 0.0122243|    1|     1|     TRUE|
|4| 181220| 333700|      1|      0| 0.0434678|    1|     1|     TRUE|
|5| 181100| 333660|      1|      0| 0.0000000|    1|     1|     TRUE|
|6| 181140| 333660|      1|      0| 0.0122243|    1|     1|     TRUE|

This is with R version 4.0.1, sp version "1.4-2".

Best,

Tyler

**Comment by edzer** [comment]
No, `data.frame(meuse.grid)` does this, I don't see why. Try `head(meuse.grid)`, or `as.data.frame(meuse.grid)[1:6,]` to verify.

**Comment by plantarum** [comment]
Thanks!
