### ISSUE TITLE
Better print method

### ISSUE THREAD

**Issue by hadley** [edzer/sp#9]
The current print method is very frustating because it prints so much information. It's a big pain if you accidentally print an sp object. A method that printed just a summary would be nice.

**Comment by edzer** [comment]
If you load `raster` after `sp` you get the behavior you want. This always frustrates me, because what should I do if I want to print the whole object? Why not use `summary` when you want to summarize?

**Comment by hadley** [comment]
I really don't believe that print should display the entire object, because it's rarely what you want, and it's the default when you enter the name of a variable on the console (have you ever actually wanted to print the first 10,000 rows of a data frame?).  I think `summary()` is best reserved for statistical summaries.

**Comment by edzer** [comment]
Why don't you set `options(max.print=xxx)` to some smaller number, then, maybe in .Rprofile? The `print` methods in `raster` do exactly that to `Spatial` objects: print statistical summaries...

**Comment by hadley** [comment]
Setting `options(max.print=10)` helps a little, but because the each individual polygon is long, you still get a lot of output. It also seems buggy, truncating all of the rows of the data frame:

```
Slot "data":
    id_num                 name         id version start_date   end_date
                                                                                                                                                                                                                         change
                                                                                                                                    citation
     start_n    end_n area_sqmi             terr_type                             full_name abbr_name
                           name_start start_posix  end_posix
 [ reached getOption("max.print") -- omitted 28 rows ]
```

Loading raster for the side effect of changing the print method seems like a bad idea. Why not include a helpful print method in sp?

**Comment by edzer** [comment]
I get your point, and am also not so happy with what we have. But what is helpful? For some if it looks pretty, for others if it doesn't obfuscate what it is. Let's discuss next week.

**Comment by hadley** [comment]
Another more radical option would be to ditch Spatial*DataFrame and store the spatial objects directly in the data frame (as a list column). Let's talk about that next week.

**Comment by edzer** [comment]
... which is the gist of the https://github.com/edzer/sfr proposal, and my Wednesday talk.

**Comment by hadley** [comment]
Hmmm, I did read that, but I didn't get the impression that it involved list-columns. Will definitely be easiest to discuss in person.

**Comment by Robinlovelace** [comment]
Out of interest, was there a discussion and was there an outcome from it if there was one? Interesting discussion I just came across!

**Comment by edzer** [comment]
Yes, we discussed the above and how printing methods for simple feature objects could be done; Package sf prints simple feature column in a `data.frame` nicely using `format`, and in a `tibble` using `type_sum` and `obj_sum` methods for tibbles with simple feature columns. We also discussed interfacing  spatial databases using WKB; sf now has fast r/w to/from WKB (in C++), see http://r-spatial.org/r/2016/09/01/bm.html, I'm now exploring rgdal and GEOS bridges - having WKB i/o might simplify this considerably, when comparing to the sp (i.e. rgdal, rgeos) code bases.

**Comment by Robinlovelace** [comment]
Awesome stuff Edzer, sounds like great progress. Thanks so much for building **sp** and working on keeping it up-to-date with the latest ideas and technologies in GIS.

**Comment by ben519** [comment]
Came looking for this.  I try to use `head(my_sf_obj)` when I want to view a simple-features object, but sometimes I forget and accidentally print the whole thing.  If the print method could be improved to prevent this, it'd save me a lot of frustration.  I love the package otherwise.

Additionally, I'm a big fan of how data.table's print method works.  By default it prints the first 5 and last 5 rows of a dataset, but you can call `print(dt, n=100)` or something similar to print more rows.  Typically the first and last rows of data tend to be very different, so you get a lot of info inspecting data that way.
