### ISSUE TITLE
Removing a variable from an empty SPDF fails

### ISSUE THREAD

**Issue by rhijmans** [edzer/sp#95]
Removing a variable in a SPDF fails when it is empty. I get this error in code that used to work, so perhaps it is newly introduced. Not too relevant for interactive use, but it would be nice not to have to work around it in other functions.

```
#OK
library(rgdal)
nc <- readOGR(system.file("shapes/sids.shp", package="maptools")[1])
names(nc)
nc$AREA <- NULL
names(nc)

# fail
nc <- readOGR(system.file("shapes/sids.shp", package="maptools")[1])
nc <- nc[0,]
nc$AREA <- NULL
#Error in h(simpleError(msg, call)) : 
#  error in evaluating the argument 'x' in selecting a method for function 'coordnames': subscript out of bounds

# also fails
nc[, names(nc)[-1]]
#Error in nc[, names(nc)[-1]] : 
#  cannot get a slot ("Polygons") from an object of type "NULL"

# it works a the data.frame
d <- data.frame(nc)
d$AREA <- NULL

```

**Comment by edzer** [comment]
If this is a regression I'm willing to look into it, but then please report with which version of `sp` this worked with. Otherwise, `Spatial*DataFrame`s are not `data.frame`s. `sf` objects are.

**Comment by rhijmans** [comment]
I will settle for using this approach `nc@data$AREA <- NULL`
